#!/usr/bin/env python3
"""Generate a drift-checked description of the current Portfolio Brain architecture."""
from __future__ import annotations
import argparse,json
from pathlib import Path

from dashboard.live_state_bridge import EVIDENCE_SEMANTICS
from hunting.repo_scout_intake import MAX_INTAKE,SOURCE_PATH,SOURCE_REPOSITORY
from adapters.abvm_health import HEALTH_WORKFLOW_PATH

ROOT=Path(__file__).resolve().parents[1]
OUTPUT=ROOT/"docs/CURRENT_SYSTEM_STATUS.md"

def load(path):
    return json.loads((ROOT/path).read_text(encoding="utf-8"))

def render()->str:
    operating=load("operations/OPERATING_MODE_POLICY.json")
    status=load("operations/OPERATING_MODE_STATUS.json")
    boundaries=load("governance/boundaries.json")
    projects=load("registry/projects.json")["projects"]
    adapters=load("adapters/ADAPTER_REGISTRY.json")["adapters"]
    caps={row["project_id"]:row for row in boundaries["project_capabilities"]}
    abvm=boundaries["constrained_integrations"]["PRJ-006"]
    gmail=boundaries["actions"]["CUSTOMER_EMAIL_GMAIL"]
    enabled=sum(1 for row in adapters if row["enabled"])
    downstream_candidate=sum(1 for pid,row in caps.items() if pid!="PRJ-000" and row["CANDIDATE_PR"]["allowed"])
    lines=[
      "# Portfolio Brain — Current System Status",
      "",
      "> GENERATED from authoritative machine configuration. Do not edit this file directly; run python -m operations.render_current_system_status.",
      "",
      "## Scope and acceptance",
      "",
      f"- Historical Steps 0–25 operating baseline: **{status['status']}**.",
      "- The September 30 automation-audit remediation is a separate acceptance track. This file describes implemented architecture and does **not** mark issue #210 steps complete; tracker evidence remains authoritative.",
      "",
      "## Authority model",
      "",
      f"- Authority model: {boundaries['authority_model']}; default effect: {boundaries['default_effect']}.",
      f"- Registered projects: **{len(projects)}**; enabled read-only repository adapters: **{enabled}/{len(adapters)}**.",
      f"- Downstream projects inheriting Portfolio Brain candidate-PR authority: **{downstream_candidate}**.",
      f"- Production deployment: {boundaries['actions']['PRODUCTION_DEPLOYMENT']['decision']}.",
      f"- Financial actions: {boundaries['actions']['FINANCIAL_ACTION']['decision']}; destructive actions: {boundaries['actions']['DESTRUCTIVE_ACTION']['decision']}.",
      f"- Live trading: {boundaries['actions']['LIVE_TRADING']['decision']}.",
      f"- Pages: {boundaries['actions']['PAGES_PUBLICATION']['decision']} / publication-only={str(boundaries['actions']['PAGES_PUBLICATION']['publication_only']).lower()} / production-deploy-authority={str(boundaries['actions']['PAGES_PUBLICATION']['production_deploy_authority']).lower()}.",
      f"- Gmail/customer email: {gmail['decision']} via {gmail['policy_ref']}; required for core autonomy={str(gmail['core_runtime_dependency']).lower()}.",
      f"- Interactive ChatGPT required for core runtime={str(operating['interactive_chatgpt_runtime_dependency']).lower()}; any external connector required for core autonomy={str(status['core_autonomy_external_connector_dependency']).lower()}.",
      "",
      "## Runtime project integration",
      "",
      "- Repository observation remains OBSERVE-only; project forwarding performs no network write, mutation, deployment, or external action.",
      "- Runtime emits and persists project_forwarding_state.json plus a sanitized forwarding receipt inside portfolio-runtime-state; exact revision/project delivery keys suppress duplicates.",
      f"- REPO-001 scout intake source: {SOURCE_REPOSITORY}/{SOURCE_PATH} at an exact source revision; maximum candidates per cycle: **{MAX_INTAKE}**.",
      "- REPO-001 output is candidate input only; the existing Hunter still performs exact-revision inspection, rights handling, ranking, proposal gating, and verification. No second Hunter exists.",
      "- REPO-001 license metadata is carried as provenance into pre-verification intake; intake does not create a separate SPDX allowlist or grant rights/reuse/value authority.",
      f"- ABVM (PRJ-006 / {abvm['repository_id']}) repository forwarding scope: {', '.join(caps['PRJ-006']['READ_OBSERVE']['scope'])}.",
      f"- ABVM automation evidence scope: {', '.join(abvm['allowed_evidence'])}; source: exact-head GitHub Actions run from {HEALTH_WORKFLOW_PATH}; persisted payload: {abvm['persisted_payload']}.",
      f"- ABVM child-facing mutation={str(abvm['child_facing_mutation']).lower()}, deployment authority={str(abvm['deployment_authority']).lower()}, school-content publication authority={str(abvm['school_content_publication_authority']).lower()}.",
      "",
      "## Evidence semantics",
      "",
      f"- Heartbeat: {EVIDENCE_SEMANTICS['heartbeat']}.",
      f"- Notification: {EVIDENCE_SEMANTICS['notification']}.",
      f"- Pages: {EVIDENCE_SEMANTICS['pages']}.",
      f"- Technical verification credit from heartbeat/notification/Pages: **{str(EVIDENCE_SEMANTICS['technical_verification_credit']).lower()}**.",
      f"- Market verification credit from heartbeat/notification/Pages: **{str(EVIDENCE_SEMANTICS['market_verification_credit']).lower()}**.",
      f"- Revenue verification credit from heartbeat/notification/Pages: **{str(EVIDENCE_SEMANTICS['revenue_verification_credit']).lower()}**.",
      "- The command center exposes per-source status, age/freshness threshold, source run/head, state sequence, canonical state hash, restore status, and error class; stale, fallback, or blocked sources stay visibly non-live.",
      "",
      "## Acceptance gates",
      "",
      "- Candidate implementation is not remediation completion.",
      "- Step acceptance still requires the tracker-defined regression coverage, Foundation success, exact-head hosted verifier App 5121826 success, and controlled/live proof where required.",
      "- Protected integration may not bypass repository rules, and neither forwarding, publication, notification, nor heartbeat telemetry creates evidence it did not observe.",
      ""
    ]
    return "\n".join(lines)

def main():
    ap=argparse.ArgumentParser();ap.add_argument("--check",action="store_true");args=ap.parse_args()
    expected=render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8")!=expected:
            raise SystemExit("docs/CURRENT_SYSTEM_STATUS.md drifted from authoritative configuration")
        print("current system status: PASS")
        return
    OUTPUT.write_text(expected,encoding="utf-8")
    print(str(OUTPUT.relative_to(ROOT)))

if __name__=="__main__":main()
